// Generated from the CSS module class names. Regenerate when classes change.
declare const styles: {
  readonly accountLink: string
  readonly badge: string
  readonly badgeBrand: string
  readonly badgeOff: string
  readonly badgeOk: string
  readonly badgeWarn: string
  readonly brand: string
  readonly bubble: string
  readonly bubbleAdmin: string
  readonly bubbleBot: string
  readonly bubbleUser: string
  readonly buttonDanger: string
  readonly buttonPrimary: string
  readonly buttonSecondary: string
  readonly card: string
  readonly cardHint: string
  readonly cardLabel: string
  readonly cardValue: string
  readonly cards: string
  readonly chatBadges: string
  readonly bubbleWarn: string
  readonly chatClosed: string
  readonly chatForm: string
  readonly chatNoResults: string
  readonly chatSearch: string
  readonly chatSendError: string
  readonly templateOption: string
  readonly chatHeader: string
  readonly chatLayout: string
  readonly chatList: string
  readonly chatMessages: string
  readonly chatName: string
  readonly chatPanel: string
  readonly chatPreview: string
  readonly chatSide: string
  readonly chips: string
  readonly confirmActions: string
  readonly confirmDialog: string
  readonly content: string
  readonly empty: string
  readonly error: string
  readonly filters: string
  readonly form: string
  readonly formGrid: string
  readonly iconBadge: string
  readonly iconPicker: string
  readonly iconSelected: string
  readonly keywords: string
  readonly list: string
  readonly listItem: string
  readonly menuButton: string
  readonly muted: string
  readonly notice: string
  readonly noticeLink: string
  readonly noticeList: string
  readonly noticeState: string
  readonly overlay: string
  readonly pageHeader: string
  readonly pagination: string
  readonly paginationCompact: string
  readonly paginationLong: string
  readonly paginationPages: string
  readonly paginationShort: string
  readonly section: string
  readonly shell: string
  readonly sidebar: string
  readonly sidebarFooter: string
  readonly sidebarOpen: string
  readonly srOnlyLabel: string
  readonly success: string
  readonly table: string
  readonly tag: string
  readonly tagEditor: string
  readonly toolbar: string
  readonly topActions: string
  readonly topbar: string
}
export default styles
