// Generated from the CSS module class names. Regenerate when classes change.
declare const styles: {
  readonly actions: string
  readonly alertError: string
  readonly alertOk: string
  readonly alertWarn: string
  readonly badgeBrand: string
  readonly badgeDanger: string
  readonly badgeNeutral: string
  readonly badgeOk: string
  readonly badgeWarn: string
  readonly badges: string
  readonly buttonDanger: string
  readonly buttonPrimary: string
  readonly buttonSecondary: string
  readonly chosen: string
  readonly combo: string
  readonly comboEmpty: string
  readonly comboList: string
  readonly comboOption: string
  readonly facts: string
  readonly field: string
  readonly fieldError: string
  readonly filterGrid: string
  readonly formGrid: string
  readonly hint: string
  readonly linkButton: string
  readonly muted: string
  readonly panel: string
  readonly resultBar: string
  readonly segmented: string
  readonly sheet: string
  readonly sheetCard: string
  readonly sheetWide: string
  readonly slot: string
  readonly slots: string
  readonly srOnly: string
  readonly sub: string
  readonly table: string
  readonly tableWrap: string
  readonly wide: string
}
export default styles
