// Generated from the CSS module class names. Regenerate when classes change.
declare const styles: {
  readonly agenda: string
  readonly blocks: string
  readonly cell: string
  readonly choice: string
  readonly config: string
  readonly control: string
  readonly day: string
  readonly dayBody: string
  readonly dayHeading: string
  readonly dayOff: string
  readonly dayPanel: string
  readonly dayTab: string
  readonly dayTabDate: string
  readonly dayTabName: string
  readonly dayTabs: string
  readonly dayToggle: string
  readonly days: string
  readonly empty: string
  readonly general: string
  readonly grid: string
  readonly gridWrap: string
  readonly hint: string
  readonly hourCol: string
  readonly interval: string
  readonly legend: string
  readonly nav: string
  readonly navButton: string
  readonly navLabel: string
  readonly navTitle: string
  readonly range: string
  readonly srOnly: string
  readonly status: string
  readonly statusError: string
  readonly swatch: string
  readonly textButton: string
  readonly time: string
  readonly times: string
}
export default styles
