-- Forward-only Argentina launch baseline. Historical migrations are inventory
-- input only; this file is the sole selected additive shape for this slice.
CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
  "id" TEXT NOT NULL,
  "checksum" TEXT NOT NULL,
  "finished_at" TIMESTAMP(3),
  "migration_name" TEXT NOT NULL,
  "logs" TEXT,
  "rolled_back_at" TIMESTAMP(3),
  "started_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "applied_steps_count" INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT "_prisma_migrations_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "TusTenant" ("id" TEXT NOT NULL, "slug" TEXT NOT NULL, "name" TEXT NOT NULL, "status" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusTenant_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "User" ("id" TEXT NOT NULL, "email" TEXT NOT NULL, "normalizedEmail" TEXT NOT NULL, "displayName" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "Account" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "roles" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], "status" TEXT NOT NULL, "emailVerifiedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Account_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "Session" ("id" TEXT NOT NULL, "accountId" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "deviceId" TEXT NOT NULL, "accessTokenDigest" TEXT NOT NULL, "roles" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], "permissions" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], "createdAt" TIMESTAMP(3) NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "revokedAt" TIMESTAMP(3), CONSTRAINT "Session_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "Membership" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "workspaceId" TEXT NOT NULL, "userId" TEXT NOT NULL, "role" TEXT NOT NULL, "roleIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], "status" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Membership_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TenantRole" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "name" TEXT NOT NULL, "permissions" TEXT[] NOT NULL, "resourceScopes" TEXT[] NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TenantRole_pkey" PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "TusMerchant" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "merchantId" TEXT NOT NULL, "cohort" TEXT NOT NULL, "locationId" TEXT NOT NULL, "timezone" TEXT NOT NULL, "staffRoles" TEXT[] NOT NULL, "operatingPolicyVersion" TEXT NOT NULL, "status" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusMerchant_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusProduct" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "sku" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT NOT NULL, "category" TEXT NOT NULL, "status" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusProduct_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusService" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "serviceCode" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT NOT NULL, "durationMinutes" INTEGER NOT NULL, "capacity" INTEGER NOT NULL, "status" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusService_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusListing" ("id" TEXT NOT NULL, "contractVersion" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "merchantId" TEXT NOT NULL, "kind" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT NOT NULL, "cohort" TEXT NOT NULL, "locationId" TEXT NOT NULL, "currency" TEXT NOT NULL, "price" BIGINT NOT NULL, "availabilityVersion" INTEGER NOT NULL, "published" BOOLEAN NOT NULL, "policyVersion" TEXT NOT NULL, "stock" INTEGER, "durationMinutes" INTEGER, "capacity" INTEGER, "workingHours" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusListing_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusInventory" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "productId" TEXT NOT NULL, "quantity" INTEGER NOT NULL, "reserved" INTEGER NOT NULL, "version" INTEGER NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusInventory_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusCalendar" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "serviceId" TEXT NOT NULL, "name" TEXT NOT NULL, "timezone" TEXT NOT NULL, "status" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusCalendar_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusCalendarRule" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "calendarId" TEXT NOT NULL, "weekday" INTEGER NOT NULL, "startsAt" TEXT NOT NULL, "endsAt" TEXT NOT NULL, "capacity" INTEGER NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusCalendarRule_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusCalendarException" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "calendarId" TEXT NOT NULL, "startsAt" TIMESTAMP(3) NOT NULL, "endsAt" TIMESTAMP(3) NOT NULL, "reason" TEXT NOT NULL, "status" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusCalendarException_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusBooking" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "bookingId" TEXT NOT NULL, "serviceId" TEXT NOT NULL, "calendarId" TEXT NOT NULL, "customerId" TEXT NOT NULL, "startsAt" TIMESTAMP(3) NOT NULL, "endsAt" TIMESTAMP(3) NOT NULL, "status" TEXT NOT NULL, "version" INTEGER NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusBooking_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusCommitment" ("id" TEXT NOT NULL, "contractVersion" TEXT NOT NULL, "commitmentId" TEXT NOT NULL, "cartId" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "merchantId" TEXT NOT NULL, "context" TEXT NOT NULL, "amount" BIGINT NOT NULL, "currency" TEXT NOT NULL, "status" TEXT NOT NULL, "lineIds" TEXT[] NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusCommitment_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusCommitmentTransition" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "commitmentId" TEXT NOT NULL, "fromStatus" TEXT NOT NULL, "toStatus" TEXT NOT NULL, "version" INTEGER NOT NULL, "actorId" TEXT NOT NULL, "correlationId" TEXT NOT NULL, "reason" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusCommitmentTransition_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusCommitmentCompensation" ("id" TEXT NOT NULL, "compensationId" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "commitmentId" TEXT NOT NULL, "actorId" TEXT NOT NULL, "correlationId" TEXT NOT NULL, "amount" BIGINT NOT NULL, "currency" TEXT NOT NULL, "reason" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusCommitmentCompensation_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusMarketplaceCommitment" ("id" TEXT NOT NULL, "contractVersion" TEXT NOT NULL, "commitmentId" TEXT NOT NULL, "cartId" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "merchantId" TEXT NOT NULL, "listingId" TEXT NOT NULL, "context" TEXT NOT NULL, "lineIds" TEXT[] NOT NULL, "quantity" INTEGER NOT NULL, "amount" BIGINT NOT NULL, "currency" TEXT NOT NULL, "status" TEXT NOT NULL, "availabilityVersion" INTEGER NOT NULL, "policyVersion" TEXT NOT NULL, "slotStart" TIMESTAMP(3), "slotEnd" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusMarketplaceCommitment_pkey" PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "TusPaymentIntent" ("id" TEXT NOT NULL, "contractVersion" TEXT NOT NULL, "paymentId" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "commitmentId" TEXT NOT NULL, "provider" TEXT NOT NULL, "providerReference" TEXT, "providerStatus" TEXT NOT NULL, "commercialStatus" TEXT NOT NULL, "amount" BIGINT NOT NULL, "currency" TEXT NOT NULL, "idempotencyKey" TEXT NOT NULL, "correlationId" TEXT NOT NULL, "credentialsCollected" BOOLEAN NOT NULL DEFAULT FALSE, "source" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusPaymentIntent_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusPaymentWebhookEvent" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "provider" TEXT NOT NULL, "providerEventId" TEXT NOT NULL, "signature" TEXT NOT NULL, "occurredAt" TIMESTAMP(3) NOT NULL, "payload" JSONB NOT NULL, "status" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusPaymentWebhookEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusCommissionSnapshot" ("id" TEXT NOT NULL, "contractVersion" TEXT NOT NULL, "snapshotId" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "commitmentId" TEXT NOT NULL, "context" TEXT NOT NULL, "grossAmount" BIGINT NOT NULL, "deductions" BIGINT NOT NULL, "commissionableBase" BIGINT NOT NULL, "rateBps" INTEGER NOT NULL, "ruleVersion" TEXT NOT NULL, "commissionAmount" BIGINT NOT NULL, "netAmount" BIGINT NOT NULL, "currency" TEXT NOT NULL, "providerReference" TEXT NOT NULL, "evidenceId" TEXT NOT NULL, "ledgerStatus" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusCommissionSnapshot_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusLedgerEntry" ("id" TEXT NOT NULL, "entryId" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "commitmentId" TEXT NOT NULL, "entryType" TEXT NOT NULL, "amount" BIGINT NOT NULL, "currency" TEXT NOT NULL, "linkedEntryId" TEXT, "reason" TEXT NOT NULL, "immutable" BOOLEAN NOT NULL DEFAULT TRUE, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusLedgerEntry_pkey" PRIMARY KEY ("id"), CONSTRAINT "TusLedgerEntry_immutable_check" CHECK ("immutable" = TRUE));
CREATE TABLE IF NOT EXISTS "TusFinancialEvidence" ("id" TEXT NOT NULL, "contractVersion" TEXT NOT NULL, "evidenceId" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "commitmentId" TEXT NOT NULL, "actorId" TEXT NOT NULL, "correlationId" TEXT NOT NULL, "kind" TEXT NOT NULL, "occurredAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusFinancialEvidence_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusFinancialConfirmation" ("id" TEXT NOT NULL, "confirmationId" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "commitmentId" TEXT NOT NULL, "actorId" TEXT NOT NULL, "correlationId" TEXT NOT NULL, "confirmedAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusFinancialConfirmation_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusFinancialFreeze" ("id" TEXT NOT NULL, "freezeId" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "commitmentId" TEXT NOT NULL, "reason" TEXT NOT NULL, "actorId" TEXT NOT NULL, "correlationId" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT TRUE, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusFinancialFreeze_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusReconciliationRecord" ("id" TEXT NOT NULL, "reconciliationId" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "commitmentId" TEXT NOT NULL, "providerReference" TEXT NOT NULL, "providerAmount" BIGINT NOT NULL, "evidenceId" TEXT NOT NULL, "actorId" TEXT NOT NULL, "correlationId" TEXT NOT NULL, "status" TEXT NOT NULL, "reason" TEXT NOT NULL, "deterministic" BOOLEAN NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusReconciliationRecord_pkey" PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "TusWhatsAppConsent" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "recipientId" TEXT NOT NULL, "status" TEXT NOT NULL, "source" TEXT NOT NULL, "grantedAt" TIMESTAMP(3) NOT NULL, "revokedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusWhatsAppConsent_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusWhatsAppMessage" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "messageId" TEXT NOT NULL, "recipientId" TEXT NOT NULL, "template" TEXT NOT NULL, "templateVersion" TEXT NOT NULL, "consentId" TEXT NOT NULL, "status" TEXT NOT NULL, "correlationId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusWhatsAppMessage_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusWhatsAppWebhookEvent" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "providerEventId" TEXT NOT NULL, "signature" TEXT NOT NULL, "occurredAt" TIMESTAMP(3) NOT NULL, "status" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusWhatsAppWebhookEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusWhatsAppAudit" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "action" TEXT NOT NULL, "outcome" TEXT NOT NULL, "actorId" TEXT NOT NULL, "senderId" TEXT NOT NULL, "correlationId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusWhatsAppAudit_pkey" PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "TusInvoice" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "invoiceId" TEXT NOT NULL, "commitmentId" TEXT NOT NULL, "currency" TEXT NOT NULL, "subtotal" BIGINT NOT NULL, "taxAmount" BIGINT NOT NULL, "feeAmount" BIGINT NOT NULL, "total" BIGINT NOT NULL, "status" TEXT NOT NULL, "taxReference" TEXT, "issuedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusInvoice_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusInvoiceLine" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "invoiceId" TEXT NOT NULL, "description" TEXT NOT NULL, "quantity" INTEGER NOT NULL, "unitMinor" BIGINT NOT NULL, "taxMinor" BIGINT NOT NULL, "totalMinor" BIGINT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusInvoiceLine_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusCreditNote" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "creditNoteId" TEXT NOT NULL, "invoiceId" TEXT NOT NULL, "currency" TEXT NOT NULL, "amountMinor" BIGINT NOT NULL, "reason" TEXT NOT NULL, "status" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusCreditNote_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusSubscription" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "subscriptionId" TEXT NOT NULL, "customerId" TEXT NOT NULL, "currency" TEXT NOT NULL, "amountMinor" BIGINT NOT NULL, "interval" TEXT NOT NULL, "status" TEXT NOT NULL, "cancelledAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusSubscription_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusTaxProfile" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "partyId" TEXT NOT NULL, "taxIdentity" TEXT NOT NULL, "taxCategory" TEXT NOT NULL, "status" TEXT NOT NULL, "evidenceRef" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusTaxProfile_pkey" PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "AuditEvent" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "actorId" TEXT, "correlationId" TEXT NOT NULL, "eventType" TEXT NOT NULL, "outcome" TEXT NOT NULL, "metadata" JSONB NOT NULL, "occurredAt" TIMESTAMP(3) NOT NULL, "retentionUntil" TIMESTAMP(3), CONSTRAINT "AuditEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusMarketplaceAudit" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "actorId" TEXT NOT NULL, "correlationId" TEXT NOT NULL, "action" TEXT NOT NULL, "resourceType" TEXT NOT NULL, "resourceId" TEXT NOT NULL, "outcome" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusMarketplaceAudit_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "OutboxEvent" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "aggregateType" TEXT NOT NULL, "aggregateId" TEXT NOT NULL, "eventType" TEXT NOT NULL, "payload" JSONB NOT NULL, "status" TEXT NOT NULL, "attempts" INTEGER NOT NULL DEFAULT 0, "availableAt" TIMESTAMP(3) NOT NULL, "lastError" TEXT, "createdAt" TIMESTAMP(3) NOT NULL, "publishedAt" TIMESTAMP(3), "claimId" TEXT, "claimUntil" TIMESTAMP(3), CONSTRAINT "OutboxEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusSupportOutbox" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "eventId" TEXT NOT NULL, "correlationId" TEXT NOT NULL, "eventType" TEXT NOT NULL, "aggregateId" TEXT NOT NULL, "payload" JSONB NOT NULL, "status" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusSupportOutbox_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusJob" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "jobId" TEXT NOT NULL, "jobType" TEXT NOT NULL, "status" TEXT NOT NULL, "attempts" INTEGER NOT NULL, "availableAt" TIMESTAMP(3) NOT NULL, "claimId" TEXT, "claimUntil" TIMESTAMP(3), "payload" JSONB NOT NULL, "lastError" TEXT, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusJob_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusDeadLetter" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "jobId" TEXT NOT NULL, "reason" TEXT NOT NULL, "payload" JSONB NOT NULL, "correlationId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusDeadLetter_pkey" PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "TusDeliveryZone" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "zoneId" TEXT NOT NULL, "name" TEXT NOT NULL, "postalCodes" TEXT[] NOT NULL, "active" BOOLEAN NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusDeliveryZone_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusDeliveryShift" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "shiftId" TEXT NOT NULL, "zoneId" TEXT NOT NULL, "startsAt" TIMESTAMP(3) NOT NULL, "endsAt" TIMESTAMP(3) NOT NULL, "operatorIds" TEXT[] NOT NULL, "status" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusDeliveryShift_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusDeliveryTask" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "taskId" TEXT NOT NULL, "commitmentId" TEXT NOT NULL, "merchantId" TEXT NOT NULL, "context" TEXT NOT NULL, "zoneId" TEXT NOT NULL, "shiftId" TEXT NOT NULL, "operatorId" TEXT, "status" TEXT NOT NULL, "version" INTEGER NOT NULL, "proof" JSONB, "incident" JSONB, "settlementClaim" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusDeliveryTask_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusDeliveryProof" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "proofId" TEXT NOT NULL, "taskId" TEXT NOT NULL, "commitmentId" TEXT NOT NULL, "recipientName" TEXT NOT NULL, "capturedAt" TIMESTAMP(3) NOT NULL, "evidenceSource" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusDeliveryProof_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusDeliveryIncident" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "incidentId" TEXT NOT NULL, "taskId" TEXT NOT NULL, "reason" TEXT NOT NULL, "status" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusDeliveryIncident_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusDeliveryAudit" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "auditId" TEXT NOT NULL, "actorId" TEXT NOT NULL, "correlationId" TEXT NOT NULL, "action" TEXT NOT NULL, "resourceType" TEXT NOT NULL, "resourceId" TEXT NOT NULL, "outcome" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusDeliveryAudit_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusDeliveryOutbox" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "eventId" TEXT NOT NULL, "correlationId" TEXT NOT NULL, "eventType" TEXT NOT NULL, "aggregateId" TEXT NOT NULL, "payload" JSONB NOT NULL, "status" TEXT NOT NULL, "attempts" INTEGER NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusDeliveryOutbox_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusPosOperation" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "operationId" TEXT NOT NULL, "idempotencyKey" TEXT NOT NULL, "schemaVersion" TEXT NOT NULL, "actorId" TEXT NOT NULL, "deviceId" TEXT NOT NULL, "shiftId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, "expectedVersion" INTEGER, "kind" TEXT NOT NULL, "context" TEXT NOT NULL, "amount" BIGINT NOT NULL, "currency" TEXT NOT NULL, "response" JSONB, CONSTRAINT "TusPosOperation_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusPosReceipt" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "receiptId" TEXT NOT NULL, "operationId" TEXT NOT NULL, "kind" TEXT NOT NULL, "context" TEXT NOT NULL, "amount" BIGINT NOT NULL, "currency" TEXT NOT NULL, "status" TEXT NOT NULL, "source" TEXT NOT NULL, "providerCapture" TEXT NOT NULL, "settlement" TEXT NOT NULL, "integrityHash" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusPosReceipt_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusPosDevice" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "deviceId" TEXT NOT NULL, "label" TEXT NOT NULL, "fingerprint" TEXT NOT NULL, "status" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusPosDevice_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusPosSession" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "sessionId" TEXT NOT NULL, "deviceId" TEXT NOT NULL, "actorId" TEXT NOT NULL, "shiftId" TEXT NOT NULL, "status" TEXT NOT NULL, "openedAt" TIMESTAMP(3) NOT NULL, "closedAt" TIMESTAMP(3), CONSTRAINT "TusPosSession_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusPosConflict" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "conflictId" TEXT NOT NULL, "operationId" TEXT NOT NULL, "reason" TEXT NOT NULL, "expectedVersion" INTEGER, "actualVersion" INTEGER, "status" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusPosConflict_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusPosVersion" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "shiftId" TEXT NOT NULL, "version" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusPosVersion_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusPosOutbox" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "eventId" TEXT NOT NULL, "eventType" TEXT NOT NULL, "aggregateId" TEXT NOT NULL, "payload" JSONB NOT NULL, "status" TEXT NOT NULL, "attempts" INTEGER NOT NULL, "availableAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastError" TEXT, "claimId" TEXT, "claimUntil" TIMESTAMP(3), "publishedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusPosOutbox_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusPosAudit" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "auditId" TEXT NOT NULL, "actorId" TEXT NOT NULL, "correlationId" TEXT NOT NULL, "action" TEXT NOT NULL, "operationId" TEXT NOT NULL, "outcome" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusPosAudit_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "TusHardeningFixture" ("id" TEXT NOT NULL, "tag" TEXT NOT NULL, "version" TEXT NOT NULL, "runId" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "actorId" TEXT NOT NULL, "productListingId" TEXT NOT NULL, "serviceListingId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TusHardeningFixture_pkey" PRIMARY KEY ("id"));

DO $$
DECLARE table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'TusListing', 'TusCommitment', 'TusCommitmentCompensation',
    'TusMarketplaceCommitment', 'TusPaymentIntent', 'TusCommissionSnapshot',
    'TusLedgerEntry', 'TusReconciliationRecord', 'TusInvoice', 'TusCreditNote',
    'TusSubscription', 'TusPosOperation', 'TusPosReceipt'
  ] LOOP
    BEGIN
      EXECUTE format(
        'ALTER TABLE %I ADD CONSTRAINT %I CHECK ("currency" ~ ''^[A-Z]{3}$'')',
        table_name,
        table_name || '_currency_iso_check'
      );
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
  END LOOP;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "TusTenant_slug_key" ON "TusTenant" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "User_email_key" ON "User" ("email");
CREATE UNIQUE INDEX IF NOT EXISTS "User_normalizedEmail_key" ON "User" ("normalizedEmail");
CREATE UNIQUE INDEX IF NOT EXISTS "Account_userId_tenantId_key" ON "Account" ("userId", "tenantId");
CREATE UNIQUE INDEX IF NOT EXISTS "Session_accessTokenDigest_key" ON "Session" ("accessTokenDigest");
CREATE UNIQUE INDEX IF NOT EXISTS "Membership_workspaceId_userId_key" ON "Membership" ("workspaceId", "userId");
CREATE UNIQUE INDEX IF NOT EXISTS "TenantRole_tenantId_name_key" ON "TenantRole" ("tenantId", "name");
CREATE UNIQUE INDEX IF NOT EXISTS "TusProduct_tenantId_sku_key" ON "TusProduct" ("tenantId", "sku");
CREATE UNIQUE INDEX IF NOT EXISTS "TusService_tenantId_serviceCode_key" ON "TusService" ("tenantId", "serviceCode");
CREATE UNIQUE INDEX IF NOT EXISTS "TusInventory_tenantId_productId_key" ON "TusInventory" ("tenantId", "productId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusCalendar_tenantId_id_key" ON "TusCalendar" ("tenantId", "id");
CREATE UNIQUE INDEX IF NOT EXISTS "TusCalendarRule_tenant_calendar_time_key" ON "TusCalendarRule" ("tenantId", "calendarId", "weekday", "startsAt", "endsAt");
CREATE UNIQUE INDEX IF NOT EXISTS "TusBooking_tenantId_bookingId_key" ON "TusBooking" ("tenantId", "bookingId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusCommitment_tenantId_commitmentId_key" ON "TusCommitment" ("tenantId", "commitmentId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusMarketplaceCommitment_tenantId_commitmentId_key" ON "TusMarketplaceCommitment" ("tenantId", "commitmentId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusPaymentWebhookEvent_tenant_provider_event_key" ON "TusPaymentWebhookEvent" ("tenantId", "provider", "providerEventId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusPaymentIntent_tenantId_idempotencyKey_key" ON "TusPaymentIntent" ("tenantId", "idempotencyKey");
CREATE UNIQUE INDEX IF NOT EXISTS "TusLedgerEntry_tenantId_entryId_key" ON "TusLedgerEntry" ("tenantId", "entryId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusWhatsAppConsent_tenantId_recipientId_key" ON "TusWhatsAppConsent" ("tenantId", "recipientId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusWhatsAppMessage_tenantId_messageId_key" ON "TusWhatsAppMessage" ("tenantId", "messageId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusWhatsAppWebhookEvent_tenantId_providerEventId_key" ON "TusWhatsAppWebhookEvent" ("tenantId", "providerEventId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusInvoice_tenantId_invoiceId_key" ON "TusInvoice" ("tenantId", "invoiceId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusInvoiceLine_tenantId_id_key" ON "TusInvoiceLine" ("tenantId", "id");
CREATE UNIQUE INDEX IF NOT EXISTS "TusCreditNote_tenantId_creditNoteId_key" ON "TusCreditNote" ("tenantId", "creditNoteId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusSubscription_tenantId_subscriptionId_key" ON "TusSubscription" ("tenantId", "subscriptionId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusTaxProfile_tenantId_partyId_key" ON "TusTaxProfile" ("tenantId", "partyId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusJob_tenantId_jobId_key" ON "TusJob" ("tenantId", "jobId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusDeliveryZone_tenantId_zoneId_key" ON "TusDeliveryZone" ("tenantId", "zoneId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusDeliveryShift_tenantId_shiftId_key" ON "TusDeliveryShift" ("tenantId", "shiftId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusDeliveryTask_tenantId_taskId_key" ON "TusDeliveryTask" ("tenantId", "taskId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusDeliveryProof_tenantId_proofId_key" ON "TusDeliveryProof" ("tenantId", "proofId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusDeliveryIncident_tenantId_incidentId_key" ON "TusDeliveryIncident" ("tenantId", "incidentId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusPosOperation_tenantId_operationId_key" ON "TusPosOperation" ("tenantId", "operationId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusPosOperation_tenantId_idempotencyKey_key" ON "TusPosOperation" ("tenantId", "idempotencyKey");
CREATE UNIQUE INDEX IF NOT EXISTS "TusPosReceipt_tenantId_receiptId_key" ON "TusPosReceipt" ("tenantId", "receiptId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusPosDevice_tenantId_deviceId_key" ON "TusPosDevice" ("tenantId", "deviceId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusPosSession_tenantId_sessionId_key" ON "TusPosSession" ("tenantId", "sessionId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusPosConflict_tenantId_conflictId_key" ON "TusPosConflict" ("tenantId", "conflictId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusPosVersion_tenantId_shiftId_key" ON "TusPosVersion" ("tenantId", "shiftId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusDeliveryOutbox_tenantId_eventId_key" ON "TusDeliveryOutbox" ("tenantId", "eventId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusPosOutbox_tenantId_eventId_key" ON "TusPosOutbox" ("tenantId", "eventId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusPosAudit_tenantId_auditId_key" ON "TusPosAudit" ("tenantId", "auditId");
CREATE UNIQUE INDEX IF NOT EXISTS "TusHardeningFixture_tag_version_runId_key" ON "TusHardeningFixture" ("tag", "version", "runId");
CREATE INDEX IF NOT EXISTS "TusHardeningFixture_tenantId_idx" ON "TusHardeningFixture" ("tenantId");

DO $$ BEGIN ALTER TABLE "TusMerchant" ADD CONSTRAINT "TusMerchant_tenant_fk" FOREIGN KEY ("tenantId") REFERENCES "TusTenant" ("id") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "Account" ADD CONSTRAINT "Account_tenant_fk" FOREIGN KEY ("tenantId") REFERENCES "TusTenant" ("id") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "Session" ADD CONSTRAINT "Session_tenant_fk" FOREIGN KEY ("tenantId") REFERENCES "TusTenant" ("id") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "TenantRole" ADD CONSTRAINT "TenantRole_tenant_fk" FOREIGN KEY ("tenantId") REFERENCES "TusTenant" ("id") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "TusProduct" ADD CONSTRAINT "TusProduct_tenant_fk" FOREIGN KEY ("tenantId") REFERENCES "TusTenant" ("id") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "TusService" ADD CONSTRAINT "TusService_tenant_fk" FOREIGN KEY ("tenantId") REFERENCES "TusTenant" ("id") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "TusListing" ADD CONSTRAINT "TusListing_tenant_fk" FOREIGN KEY ("tenantId") REFERENCES "TusTenant" ("id") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "TusBooking" ADD CONSTRAINT "TusBooking_tenant_fk" FOREIGN KEY ("tenantId") REFERENCES "TusTenant" ("id") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "TusCommitment" ADD CONSTRAINT "TusCommitment_tenant_fk" FOREIGN KEY ("tenantId") REFERENCES "TusTenant" ("id") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "TusPaymentIntent" ADD CONSTRAINT "TusPaymentIntent_tenant_fk" FOREIGN KEY ("tenantId") REFERENCES "TusTenant" ("id") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "TusLedgerEntry" ADD CONSTRAINT "TusLedgerEntry_tenant_fk" FOREIGN KEY ("tenantId") REFERENCES "TusTenant" ("id") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "TusInvoice" ADD CONSTRAINT "TusInvoice_tenant_fk" FOREIGN KEY ("tenantId") REFERENCES "TusTenant" ("id") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "TusJob" ADD CONSTRAINT "TusJob_tenant_fk" FOREIGN KEY ("tenantId") REFERENCES "TusTenant" ("id") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "TusPosOperation" ADD CONSTRAINT "TusPosOperation_tenant_fk" FOREIGN KEY ("tenantId") REFERENCES "TusTenant" ("id") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "TusPosReceipt" ADD CONSTRAINT "TusPosReceipt_tenant_operation_fk" FOREIGN KEY ("tenantId", "operationId") REFERENCES "TusPosOperation" ("tenantId", "operationId") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "TusPosSession" ADD CONSTRAINT "TusPosSession_tenant_device_fk" FOREIGN KEY ("tenantId", "deviceId") REFERENCES "TusPosDevice" ("tenantId", "deviceId") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "TusDeliveryShift" ADD CONSTRAINT "TusDeliveryShift_tenant_zone_fk" FOREIGN KEY ("tenantId", "zoneId") REFERENCES "TusDeliveryZone" ("tenantId", "zoneId") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "TusDeliveryTask" ADD CONSTRAINT "TusDeliveryTask_tenant_shift_fk" FOREIGN KEY ("tenantId", "shiftId") REFERENCES "TusDeliveryShift" ("tenantId", "shiftId") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "TusDeliveryProof" ADD CONSTRAINT "TusDeliveryProof_tenant_task_fk" FOREIGN KEY ("tenantId", "taskId") REFERENCES "TusDeliveryTask" ("tenantId", "taskId") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "TusDeliveryIncident" ADD CONSTRAINT "TusDeliveryIncident_tenant_task_fk" FOREIGN KEY ("tenantId", "taskId") REFERENCES "TusDeliveryTask" ("tenantId", "taskId") NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;

INSERT INTO "_prisma_migrations" ("id", "checksum", "finished_at", "migration_name", "logs", "rolled_back_at", "started_at", "applied_steps_count")
SELECT 'tus-argentina-market-launch-marker', 'launch-migration-checksum', CURRENT_TIMESTAMP, '20260909090000_tus_argentina_market_launch', NULL, NULL, CURRENT_TIMESTAMP, 1
WHERE NOT EXISTS (SELECT 1 FROM "_prisma_migrations" WHERE "migration_name" = '20260909090000_tus_argentina_market_launch');
