// TUS assistant on the Web: ONE wire contract shared by the API and the Web client.
//
// The Web and WhatsApp are two channels over the same assistant (model, tools, knowledge base,
// confirmations, memory and permissions live in the API). What travels here is presentation: the
// text written by the model plus data the BACKEND attached from real tool results. The client
// never sends an identity: the account comes from the session; `visitorId` is a random browser id
// that only gives continuity to an anonymous (public) conversation.

export const ASISTENTE_WEB_LIMITES = { textoMin: 1, textoMax: 1000 } as const

// Random id generated by the browser (never an account, never an authority).
export const ASISTENTE_WEB_VISITANTE = /^[A-Za-z0-9_-]{16,64}$/u

export interface PrestadorAsistenteDTO {
  providerId: string
  name: string
  profession: string
  area: string
  verified: boolean
  completedJobs: number
  availability: string
}

export interface TurnoAsistenteDTO {
  startsAt: string
  endsAt: string
  durationMinutes: number
}

export interface OfertaTurnoAsistenteDTO {
  providerId: string
  name: string
  area: string
  verified: boolean
  completedJobs: number
  durationMinutes: number | null
  exact: boolean
  starts: string[]
}

export interface TarifaAsistenteDTO {
  id: string
  name: string
  durationMinutes: number
  price: number
}

// Structured data of a reply. Always built by the backend from a tool result or from the
// retrieved documents; the model only writes the text next to it.
export type AdjuntoAsistente =
  | { kind: 'providers'; providers: PrestadorAsistenteDTO[] }
  | { kind: 'slots'; providerId: string; profession: string; date: string; slots: TurnoAsistenteDTO[]; tariffs: TarifaAsistenteDTO[] }
  // Providers with their real free turnos for what the person asked. exact = false: nothing fits
  // the asked time and these are the closest starts.
  | { kind: 'appointments'; profession: string; providers: OfertaTurnoAsistenteDTO[] }
  | { kind: 'sources'; sources: { documentId: string; title: string }[] }
  // The reply needs an account; the channel offers its own way in (the Web: sign in).
  | { kind: 'sign_in' }

export type AccionAsistenteDTO =
  // Answer of a confirmation card; `id` is opaque and bound to the conversation and the account.
  | { kind: 'reply'; id: string; label: string }
  | { kind: 'link'; url: string; label: string }

export interface MensajeAsistenteDTO {
  id: string
  role: 'user' | 'assistant'
  text: string
  createdAt: string
  attachment?: AdjuntoAsistente
  actions?: AccionAsistenteDTO[]
  // The model was unavailable: the text is the safe fallback (fixed or extractive), not a
  // conversational reply.
  fallback?: boolean
}

export type IntencionAsistenteDTO = 'buscar' | 'postulaciones' | 'trabajos' | 'presupuesto' | 'reserva' | 'pago' | 'identidad' | 'conocimiento' | 'saludo' | 'otro'

// Progress of a turn, emitted while the backend is really doing each step.
export type ActividadAsistenteDTO =
  | { type: 'routing'; intent: IntencionAsistenteDTO }
  | { type: 'knowledge'; phase: 'start' | 'end' }
  | { type: 'tool'; tool: string; phase: 'start' | 'end'; ok?: boolean }

export interface SolicitudMensajeAsistente {
  // Free text, or the id of a confirmation action (`replyId`); never both empty.
  text?: string
  replyId?: string
  visitorId?: string
}

export interface RespuestaMensajeAsistente {
  conversationId: string
  authenticated: boolean
  userMessage: MensajeAsistenteDTO
  messages: MensajeAsistenteDTO[]
  // Steps the backend ran for this turn (same events the stream emits live).
  activity: ActividadAsistenteDTO[]
  degraded: boolean
}

export interface HistorialAsistente {
  conversationId: string | null
  authenticated: boolean
  messages: MensajeAsistenteDTO[]
}

// One line of the NDJSON stream (Accept: application/x-ndjson).
export type EventoStreamAsistente =
  | { type: 'accepted'; conversationId: string; userMessage: MensajeAsistenteDTO }
  | { type: 'activity'; activity: ActividadAsistenteDTO }
  | { type: 'message'; message: MensajeAsistenteDTO }
  | { type: 'done'; degraded: boolean; authenticated: boolean }
  | { type: 'error'; code: string; error: string }
