// Generated from the CSS module class names. Regenerate when classes change.
declare const styles: {
  readonly checkbox: string
  readonly counter: string
  readonly field: string
  readonly fieldError: string
  readonly fileButton: string
  readonly fileInput: string
  readonly filePicker: string
  readonly footerText: string
  readonly form: string
  readonly formError: string
  readonly formSide: string
  readonly formWrap: string
  readonly google: string
  readonly googleHint: string
  readonly input: string
  readonly inputInvalid: string
  readonly intent: string
  readonly intentOption: string
  readonly intentSelected: string
  readonly intentText: string
  readonly intentTitle: string
  readonly legend: string
  readonly link: string
  readonly linkRow: string
  readonly notice: string
  readonly passwordWrap: string
  readonly pin: string
  readonly primary: string
  readonly row2: string
  readonly separator: string
  readonly shell: string
  readonly subtitle: string
  readonly success: string
  readonly title: string
  readonly toggle: string
  readonly topBar: string
  readonly topBarBack: string
  readonly topBarBrand: string
  readonly visualContent: string
  readonly visualGrid: string
  readonly visualList: string
  readonly visualSide: string
  readonly visualTitle: string
}
export default styles
