import type { MapRequest } from './types'

// Illustrative requests (fictitious people, zone centroids of Córdoba Capital). Shown only as
// examples: the UI labels them. Images are local illustrations, not user uploads.
export const EXAMPLE_REQUESTS: MapRequest[] = [
  {
    id: 'ejemplo-1',
    category: 'plomeria',
    title: 'Pérdida de agua debajo de la bacha',
    description: 'Gotea el sifón de la cocina y se moja el mueble.',
    requesterName: 'Laura Martínez',
    approximateLocation: { lat: -31.4265, lng: -64.1874, label: 'Nueva Córdoba' },
    budgetLabel: 'Hasta $25.000',
    urgencyLabel: 'Hoy o mañana',
    createdAtLabel: 'Hace 20 min',
    images: ['/home/ejemplos/plomeria-1.svg', '/home/ejemplos/plomeria-2.svg'],
  },
  {
    id: 'ejemplo-2',
    category: 'electricidad',
    title: 'Se corta la luz al usar el horno',
    description: 'Salta la térmica cada vez que prendo el horno eléctrico.',
    requesterName: 'Martín Gómez',
    approximateLocation: { lat: -31.4125, lng: -64.165, label: 'General Paz' },
    budgetLabel: 'A convenir',
    urgencyLabel: 'Urgente',
    createdAtLabel: 'Hace 45 min',
    images: ['/home/ejemplos/electricidad-1.svg'],
  },
  {
    id: 'ejemplo-3',
    category: 'aire',
    title: 'El aire acondicionado no enfría',
    description: 'Split de 3000 frigorías, enciende pero tira aire caliente.',
    requesterName: 'Sofía Díaz',
    approximateLocation: { lat: -31.396, lng: -64.183, label: 'Alta Córdoba' },
    budgetLabel: 'Hasta $40.000',
    urgencyLabel: 'Esta semana',
    createdAtLabel: 'Hace 1 h',
    images: [],
  },
  {
    id: 'ejemplo-4',
    category: 'pintura',
    title: 'Pintar un dormitorio de 3 x 4',
    description: 'Paredes y techo, color claro. Tengo la pintura.',
    requesterName: 'Carla Ríos',
    approximateLocation: { lat: -31.427, lng: -64.197, label: 'Güemes' },
    budgetLabel: 'Hasta $60.000',
    urgencyLabel: 'Sin apuro',
    createdAtLabel: 'Hace 2 h',
    images: ['/home/ejemplos/pintura-1.svg'],
  },
  {
    id: 'ejemplo-5',
    category: 'mecanica',
    title: 'Cambio de pastillas de freno',
    description: 'Auto chico, necesito que vengan a domicilio.',
    requesterName: 'Diego Luna',
    approximateLocation: { lat: -31.37, lng: -64.23, label: 'Cerro de las Rosas' },
    budgetLabel: 'A convenir',
    urgencyLabel: 'Esta semana',
    createdAtLabel: 'Hace 3 h',
    images: [],
  },
  {
    id: 'ejemplo-6',
    category: 'otros',
    title: 'Armar un placard de melamina',
    description: 'Viene en cajas con instructivo, dos puertas corredizas.',
    requesterName: 'Valeria Sosa',
    approximateLocation: { lat: -31.452, lng: -64.176, label: 'Jardín' },
    budgetLabel: 'Hasta $30.000',
    urgencyLabel: 'Hoy o mañana',
    createdAtLabel: 'Hace 4 h',
    images: ['/home/ejemplos/otros-1.svg', '/home/ejemplos/otros-2.svg'],
  },
  {
    id: 'ejemplo-7',
    category: 'plomeria',
    title: 'Instalar un termotanque nuevo',
    description: 'Reemplazo de termotanque a gas de 80 litros.',
    requesterName: 'Pablo Ferreyra',
    approximateLocation: { lat: -31.412, lng: -64.205, label: 'Alberdi' },
    budgetLabel: 'Hasta $80.000',
    urgencyLabel: 'Esta semana',
    createdAtLabel: 'Ayer',
    images: [],
  },
]
