// Generated from the CSS module class names. Regenerate when classes change.
declare const styles: {
  readonly assistantBot: string
  readonly assistantClose: string
  readonly assistantFab: string
  readonly assistantForm: string
  readonly assistantHeader: string
  readonly assistantLink: string
  readonly assistantMessages: string
  readonly assistantOptions: string
  readonly assistantPanel: string
  readonly assistantTyping: string
  readonly assistantUser: string
  readonly avatar: string
  readonly brandLink: string
  readonly buttonGhost: string
  readonly buttonPrimary: string
  readonly buttonSecondary: string
  readonly categoryIcon: string
  readonly cellMain: string
  readonly chevron: string
  readonly field: string
  readonly footer: string
  readonly footerBottom: string
  readonly footerBrand: string
  readonly footerColumn: string
  readonly footerGrid: string
  readonly footerTagline: string
  readonly header: string
  readonly headerActions: string
  readonly headerInner: string
  readonly hero: string
  readonly hideMobile: string
  readonly hideTablet: string
  readonly label: string
  readonly list: string
  readonly main: string
  readonly mapControls: string
  readonly mapLayer: string
  readonly mapNotice: string
  readonly mapResults: string
  readonly mapSkeleton: string
  readonly marker: string
  readonly markerActive: string
  readonly menuButton: string
  readonly mobileMenu: string
  readonly nav: string
  readonly page: string
  readonly person: string
  readonly popup: string
  readonly popupActions: string
  readonly popupCategory: string
  readonly popupCta: string
  readonly popupImages: string
  readonly popupMeta: string
  readonly popupTitle: string
  readonly price: string
  readonly proBand: string
  readonly proTitle: string
  readonly providerGrid: string
  readonly providerSelected: string
  readonly row: string
  readonly rowActive: string
  readonly rowButton: string
  readonly rowCategory: string
  readonly rowText: string
  readonly rowTitle: string
  readonly search: string
  readonly searchButton: string
  readonly searchDock: string
  readonly searchInput: string
  readonly section: string
  readonly sectionActions: string
  readonly sectionHeader: string
  readonly sectionSubtitle: string
  readonly sectionTitle: string
  readonly seeAll: string
  readonly skeletonRow: string
  readonly skipLink: string
  readonly srOnly: string
  readonly state: string
  readonly step: string
  readonly stepNumber: string
  readonly stepTitle: string
  readonly steps: string
  readonly strong: string
  readonly thumb: string
  readonly thumbs: string
  readonly urgency: string
}
export default styles
