declare const styles: {
  readonly container: string
  readonly header: string
  readonly title: string
  readonly subtitle: string
  readonly filterBar: string
  readonly filterGrid: string
  readonly formGroup: string
  readonly formLabel: string
  readonly formInput: string
  readonly formSelect: string
  readonly btnSearch: string
  readonly viewControls: string
  readonly viewTabs: string
  readonly viewTab: string
  readonly viewTabActive: string
  readonly mainLayout: string
  readonly mainLayoutSplit: string
  readonly cardsGrid: string
  readonly card: string
  readonly cardImageWrapper: string
  readonly cardImage: string
  readonly cardImagePlaceholder: string
  readonly typeBadge: string
  readonly cardContent: string
  readonly cardHeader: string
  readonly cardTitle: string
  readonly ratingTag: string
  readonly starIcon: string
  readonly locationText: string
  readonly amenitiesRow: string
  readonly amenityPill: string
  readonly cardFooter: string
  readonly priceLabel: string
  readonly priceValue: string
  readonly btnDetail: string
  readonly mapContainer: string
  readonly mapMarkerPrice: string
  readonly mapMarkerPriceActive: string
  readonly popupContainer: string
  readonly popupTitle: string
  readonly popupPrice: string
  readonly popupBtn: string
  readonly galleryGrid: string
  readonly galleryMain: string
  readonly gallerySub: string
  readonly detailLayout: string
  readonly unitCard: string
  readonly unitImage: string
  readonly fallbackNotice: string
  readonly modalBackdrop: string
  readonly modalContent: string
  readonly modalHeader: string
  readonly modalTitle: string
  readonly btnClose: string
}
export default styles
