// Generated from the CSS module class names. Regenerate when classes change.
declare const styles: {
  readonly available: string
  readonly avatar: string
  readonly avatarImage: string
  readonly avatarLarge: string
  readonly avatarSm: string
  readonly back: string
  readonly bookingControl: string
  readonly bookingForm: string
  readonly bookingRow2: string
  readonly bubble: string
  readonly candidates: string
  readonly card: string
  readonly cardActions: string
  readonly cardCompact: string
  readonly cardHeading: string
  readonly cardTop: string
  readonly chat: string
  readonly check: string
  readonly chip: string
  readonly chips: string
  readonly compactFacts: string
  readonly composer: string
  readonly container: string
  readonly facts: string
  readonly filterGroup: string
  readonly filters: string
  readonly filtersToggle: string
  readonly fromAssistant: string
  readonly fromUser: string
  readonly grid: string
  readonly messages: string
  readonly modalBackdrop: string
  readonly modalCard: string
  readonly moreRow: string
  readonly muted: string
  readonly name: string
  readonly narrow: string
  readonly notice: string
  readonly options: string
  readonly panel: string
  readonly panelTitle: string
  readonly photoEditor: string
  readonly photoEditorActions: string
  readonly photoEditorBody: string
  readonly photoEditorInput: string
  readonly photoEditorPick: string
  readonly photoEditorTitle: string
  readonly profession: string
  readonly profileGrid: string
  readonly profileHead: string
  readonly requestFacts: string
  readonly requestSent: string
  readonly requester: string
  readonly requesterLabel: string
  readonly resultCount: string
  readonly searchField: string
  readonly searchRow: string
  readonly select: string
  readonly service: string
  readonly services: string
  readonly skeleton: string
  readonly srOnlyLabel: string
  readonly state: string
  readonly stateActions: string
  readonly submitHint: string
  readonly submitRow: string
  readonly subtitle: string
  readonly tarifaCard: string
  readonly tarifaCardActive: string
  readonly title: string
  readonly turnoActions: string
  readonly turnoCard: string
  readonly turnoCardNew: string
  readonly turnoData: string
  readonly turnoList: string
  readonly turnoState: string
  readonly turnoStateOff: string
  readonly turnoStateOk: string
  readonly turnoStatePending: string
  readonly verified: string
  readonly verifiedMark: string
}
export default styles
