// Generated from the CSS module class names. Regenerate when classes change.
declare const styles: {
  readonly available: string
  readonly avatar: string
  readonly avatarLarge: string
  readonly back: string
  readonly bubble: string
  readonly candidates: string
  readonly card: string
  readonly cardActions: string
  readonly cardTop: string
  readonly chat: string
  readonly check: string
  readonly chip: string
  readonly chips: string
  readonly composer: string
  readonly container: string
  readonly facts: string
  readonly filterGroup: string
  readonly filters: string
  readonly filtersToggle: string
  readonly fromAssistant: string
  readonly fromUser: string
  readonly grid: string
  readonly messages: string
  readonly moreRow: string
  readonly muted: string
  readonly name: string
  readonly narrow: string
  readonly notice: string
  readonly options: string
  readonly panel: string
  readonly panelTitle: string
  readonly profession: string
  readonly profileGrid: string
  readonly profileHead: string
  readonly resultCount: string
  readonly searchField: string
  readonly searchRow: string
  readonly select: string
  readonly service: string
  readonly services: string
  readonly skeleton: string
  readonly srOnlyLabel: string
  readonly state: string
  readonly stateActions: string
  readonly subtitle: string
  readonly title: string
  readonly verified: string
}
export default styles
